# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_ss_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ss',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
